alias 'l=ls -ltr --color=auto'
alias 'vivado=faketime -f "-5y" vivado'
#alias 'vivado_hls=faketime -f "-5y" vivado_hls'
alias '.1=cd ..'
alias '.2=cd ../..'
alias '.3=cd ../../..'
alias '.4=cd ../../../..'
alias '.5=cd ../../../../..'
alias 'grep=grep --color=auto'
alias 'md=mkdir'
alias 'tclsh=rlwrap tclsh'
alias 'tcl=rlwrap tclsh'
alias 'keepass=keepass ~/keepass.kdbx -preselect:/run/media/ckayhan/Elements1/KEEPASS/keepassxc.key'
