alias 'l=ls -ltr'
alias 'vivado=faketime -f "-5y" vivado'
alias 'vivado_hls=faketime -f "-5y" vivado_hls'
alias '.1=cd ..'
alias '.2=cd ../..'
alias '.3=cd ../../..'
alias '.4=cd ../../../..'
alias '.5=cd ../../../../..'
